DEFAULT_REGIONS = [
    "US"
]

DEFAULT_LIMIT = 20
DEFAULT_SLEEP_SEC = 10.0
DEFAULT_TREND_METHOD = "trending_searches"
DEFAULT_TREND_SOURCE = "rss"
DEFAULT_CSV_HOURS = 4
DEFAULT_CSV_SORT_BY = "traffic"
DEFAULT_FALLBACK_CATEGORY = "trend"
DEFAULT_FALLBACK_TAGS = ["topic"]
DEFAULT_RSS_INCLUDE_IMAGES = True
DEFAULT_RSS_INCLUDE_ARTICLES = True
DEFAULT_RSS_MAX_ARTICLES_PER_TREND = 10
DEFAULT_RSS_CACHE = True
